url:
  key: "913da61969a3190ba9de6b5c094a0eb4"
  location: "Bangkok"

server:
  address: ":1323"

database:
  driver: "mysql"
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "P@ssw0rd"
  dbname: "weather"

redis:
  user: "default"
  password: "mF1xm8R1VEMdljuYiphRdiCvKazw0IkK"
  host: "redis-10316.c258.us-east-1-4.ec2.redns.redis-cloud.com"
  port: "10316"
